// Copyright CERN. This software is distributed under the
// terms of the GNU General Public Licence version 3 (GPL Version 3),
// copied verbatim in the file LICENSE.txt.
// In applying this licence, CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization or
// submit itself to any jurisdiction.
// Project website: http://blond.web.cern.ch/

// GENERATED by `python -m blond.core.backends.deferred.kernel_call_records`
// from the KernelCallArgs dataclasses in kernel_call_records.py.
// Do not edit.
//
// Include after `real_t` and `index_t` are defined:
// blond_common.h on the C++ side, kernels.cu on the CUDA side.

#pragma once

#include <cstddef>
#include <cstdint>

#ifdef __CUDACC__
#define BLOND_HOST_DEVICE __host__ __device__
#else
#define BLOND_HOST_DEVICE
#endif

static_assert(sizeof(real_t) == 8, "records assume 64-bit real_t");
static_assert(sizeof(index_t) == 8, "records assume 64-bit index_t");

// Layout checks of the structs below, one line each.
#define BLOND_CHECK_SIZE(type, size) \
  static_assert(sizeof(type) == (size), "regenerate this header")
#define BLOND_CHECK_OFFSET(type, member, offset) \
  static_assert(offsetof(type, member) == (offset), \
                "regenerate this header")

enum class KernelId : std::uint32_t {
  KickSingleHarmonic = 0,
  KickMultiHarmonic = 1,
  DriftSimple = 2,
  DriftLikeLineSegment = 3,
  DriftExact = 4,
  KickInterpolated = 5,
  Histogram = 6,
};
constexpr int KERNEL_COUNT = 7;
constexpr std::size_t KERNEL_CALL_BATCH_CAPACITY_BYTES = 4064;

struct KernelCallHeader {
  KernelId kernel_id;
  // header + Args + trailing elements, multiple of 8
  std::uint32_t record_size_bytes;
};

// Plain C arrays: the layout is fixed by the numpy dtypes.
// NOLINTBEGIN(*-avoid-c-arrays)
struct KickSingleHarmonicArgs {
  real_t voltage;
  real_t omega_rf;
  real_t phi_rf;
  real_t charge;
  real_t acceleration_kick;
};
BLOND_CHECK_SIZE(KickSingleHarmonicArgs, 40);
BLOND_CHECK_OFFSET(KickSingleHarmonicArgs, voltage, 0);
BLOND_CHECK_OFFSET(KickSingleHarmonicArgs, omega_rf, 8);
BLOND_CHECK_OFFSET(KickSingleHarmonicArgs, phi_rf, 16);
BLOND_CHECK_OFFSET(KickSingleHarmonicArgs, charge, 24);
BLOND_CHECK_OFFSET(KickSingleHarmonicArgs, acceleration_kick, 32);

constexpr int MAX_RF_HARMONICS_PER_RECORD = 168;
// Followed by 3 columns of `n_rf` reals, see `harmonics_of`.
struct KickMultiHarmonicArgs {
  real_t charge;
  real_t acceleration_kick;
  std::int32_t n_rf;
  std::int32_t padding_3;
};
BLOND_CHECK_SIZE(KickMultiHarmonicArgs, 24);
BLOND_CHECK_OFFSET(KickMultiHarmonicArgs, charge, 0);
BLOND_CHECK_OFFSET(KickMultiHarmonicArgs, acceleration_kick, 8);
BLOND_CHECK_OFFSET(KickMultiHarmonicArgs, n_rf, 16);

struct DriftSimpleArgs {
  real_t T;
  real_t eta_0;
  real_t beta;
  real_t energy;
};
BLOND_CHECK_SIZE(DriftSimpleArgs, 32);
BLOND_CHECK_OFFSET(DriftSimpleArgs, T, 0);
BLOND_CHECK_OFFSET(DriftSimpleArgs, eta_0, 8);
BLOND_CHECK_OFFSET(DriftSimpleArgs, beta, 16);
BLOND_CHECK_OFFSET(DriftSimpleArgs, energy, 24);

struct DriftLikeLineSegmentArgs {
  real_t T;
  real_t eta_0;
  real_t beta;
  real_t energy;
};
BLOND_CHECK_SIZE(DriftLikeLineSegmentArgs, 32);
BLOND_CHECK_OFFSET(DriftLikeLineSegmentArgs, T, 0);
BLOND_CHECK_OFFSET(DriftLikeLineSegmentArgs, eta_0, 8);
BLOND_CHECK_OFFSET(DriftLikeLineSegmentArgs, beta, 16);
BLOND_CHECK_OFFSET(DriftLikeLineSegmentArgs, energy, 24);

struct DriftExactArgs {
  real_t T;
  real_t alpha_0;
  real_t beta;
  real_t energy;
  std::int32_t n_alpha;
  std::int32_t padding_5;
  real_t higher_alpha[8];
};
BLOND_CHECK_SIZE(DriftExactArgs, 104);
BLOND_CHECK_OFFSET(DriftExactArgs, T, 0);
BLOND_CHECK_OFFSET(DriftExactArgs, alpha_0, 8);
BLOND_CHECK_OFFSET(DriftExactArgs, beta, 16);
BLOND_CHECK_OFFSET(DriftExactArgs, energy, 24);
BLOND_CHECK_OFFSET(DriftExactArgs, n_alpha, 32);
BLOND_CHECK_OFFSET(DriftExactArgs, higher_alpha, 40);

struct KickInterpolatedArgs {
  const real_t *voltage_kick_table;
  index_t voltage_kick_table_length;
  real_t acceleration_kick;
};
BLOND_CHECK_SIZE(KickInterpolatedArgs, 24);
BLOND_CHECK_OFFSET(KickInterpolatedArgs, voltage_kick_table, 0);
BLOND_CHECK_OFFSET(KickInterpolatedArgs, voltage_kick_table_length, 8);
BLOND_CHECK_OFFSET(KickInterpolatedArgs, acceleration_kick, 16);

struct HistogramArgs {
  real_t *array_write;
  index_t array_write_length;
  real_t start;
  real_t stop;
};
BLOND_CHECK_SIZE(HistogramArgs, 32);
BLOND_CHECK_OFFSET(HistogramArgs, array_write, 0);
BLOND_CHECK_OFFSET(HistogramArgs, array_write_length, 8);
BLOND_CHECK_OFFSET(HistogramArgs, start, 16);
BLOND_CHECK_OFFSET(HistogramArgs, stop, 24);

// A macro, so the CUDA side can initialise a __device__ array
// from the same list (kernels.cu).
#define KERNEL_CALL_ARGS_SIZES_INITIALIZER \
  { \
    sizeof(KickSingleHarmonicArgs), \
    sizeof(KickMultiHarmonicArgs), \
    sizeof(DriftSimpleArgs), \
    sizeof(DriftLikeLineSegmentArgs), \
    sizeof(DriftExactArgs), \
    sizeof(KickInterpolatedArgs), \
    sizeof(HistogramArgs), \
  }
constexpr std::uint32_t KERNEL_CALL_ARGS_SIZES[KERNEL_COUNT] =
    KERNEL_CALL_ARGS_SIZES_INITIALIZER;
// NOLINTEND(*-avoid-c-arrays)

// The records are packed back to back in a byte buffer, hence the
// casts from the header to its Args and to the next header.
// NOLINTBEGIN(*-reinterpret-cast,*-pointer-arithmetic)
template <class Args>
BLOND_HOST_DEVICE inline const Args &
record_args(const KernelCallHeader *record) {
  return *reinterpret_cast<const Args *>(
      reinterpret_cast<const char *>(record) + sizeof(KernelCallHeader));
}

BLOND_HOST_DEVICE inline const KernelCallHeader *
next_record(const KernelCallHeader *record) {
  return reinterpret_cast<const KernelCallHeader *>(
      reinterpret_cast<const char *>(record) + record->record_size_bytes);
}

// The trailing columns of a KickMultiHarmonicArgs record.
struct RfHarmonics {
  const real_t *voltage;
  const real_t *omega_rf;
  const real_t *phi_rf;
};
BLOND_HOST_DEVICE inline RfHarmonics
harmonics_of(const KickMultiHarmonicArgs &args) {
  const auto *first = reinterpret_cast<const real_t *>(&args + 1);
  return {first, first + args.n_rf, first + 2 * args.n_rf};
}
// NOLINTEND(*-reinterpret-cast,*-pointer-arithmetic)

// The only switch over KernelId. `visitor(args)` resolves to the
// backend's overload for that Args type; a missing overload does
// not compile. The pragma lets a host-only visitor instantiate it
// under nvcc without a __host__ __device__ mismatch warning.
#ifdef __CUDACC__
#pragma nv_exec_check_disable
#endif
template <class Visitor>
BLOND_HOST_DEVICE inline void
visit_kernel_call(const KernelCallHeader *record, const Visitor &visitor) {
  switch (record->kernel_id) {
  case KernelId::KickSingleHarmonic:
    visitor(record_args<KickSingleHarmonicArgs>(record));
    break;
  case KernelId::KickMultiHarmonic:
    visitor(record_args<KickMultiHarmonicArgs>(record));
    break;
  case KernelId::DriftSimple:
    visitor(record_args<DriftSimpleArgs>(record));
    break;
  case KernelId::DriftLikeLineSegment:
    visitor(record_args<DriftLikeLineSegmentArgs>(record));
    break;
  case KernelId::DriftExact:
    visitor(record_args<DriftExactArgs>(record));
    break;
  case KernelId::KickInterpolated:
    visitor(record_args<KickInterpolatedArgs>(record));
    break;
  case KernelId::Histogram:
    visitor(record_args<HistogramArgs>(record));
    break;
  }
}
