"""Mirror the agent skills into root docs and the ``.claude`` folder.

``.agents/skills/`` is the single source of truth for agent-facing context.
This script keeps two mirrors of it in sync:

* the ``blond-dev`` skill body is copied (frontmatter stripped, with a
  generated-file banner prepended) into ``CLAUDE.md`` and ``AGENTS.md`` at the
  repo root, so interactive and CI/CD agents share the same context;
* the whole ``.agents/skills/`` tree is mirrored verbatim into
  ``.claude/skills/`` so Claude Code auto-discovers the same skills.

Run as a ``pre-commit`` hook: it fires when anything under ``.agents/skills/``
changes, and exits non-zero if it had to rewrite any target so the new files
get re-staged.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_SRC = ROOT / ".agents" / "skills"
SKILLS_DST = ROOT / ".claude" / "skills"
SOURCE = SKILLS_SRC / "blond-dev" / "SKILL.md"
TARGETS = (ROOT / "CLAUDE.md", ROOT / "AGENTS.md")

BANNER = (
    "<!--\n"
    "AUTO-GENERATED FILE - DO NOT EDIT.\n"
    "Source: .agents/skills/blond-dev/SKILL.md\n"
    "Regenerated by the `sync-agent-docs` pre-commit hook.\n"
    "Edit the skill, then commit; this file is rewritten automatically.\n"
    "-->\n\n"
)


def strip_frontmatter(text: str) -> str:
    """Return ``text`` without a leading YAML ``---`` frontmatter block."""
    if not text.startswith("---"):
        return text
    lines = text.splitlines(keepends=True)
    for index in range(1, len(lines)):
        if lines[index].rstrip("\n") == "---":
            return "".join(lines[index + 1 :]).lstrip("\n")
    return text


def render() -> str:
    """Build the generated document from the skill source."""
    body = strip_frontmatter(SOURCE.read_text(encoding="utf-8"))
    return BANNER + body


def sync_docs() -> list[str]:
    """Rewrite stale CLAUDE.md / AGENTS.md; return the names changed."""
    content = render()
    changed = []
    for target in TARGETS:
        old = target.read_text(encoding="utf-8") if target.exists() else None
        if old != content:
            target.write_text(content, encoding="utf-8", newline="\n")
            changed.append(target.name)
    return changed


def mirror_skills() -> list[str]:
    """Mirror ``.agents/skills/`` into ``.claude/skills/`` verbatim.

    Copies every source file whose destination is missing or differs, and
    removes any stale file or empty directory under the destination that no
    longer exists in the source. Returns the destination-relative paths that
    were created, updated, or deleted.
    """
    changed = []
    sources = {
        path.relative_to(SKILLS_SRC): path
        for path in SKILLS_SRC.rglob("*")
        if path.is_file()
    }
    for rel, src in sources.items():
        dst = SKILLS_DST / rel
        data = src.read_bytes()
        old = dst.read_bytes() if dst.exists() else None
        if old != data:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(data)
            changed.append(str(Path(".claude/skills") / rel))

    if SKILLS_DST.exists():
        for path in sorted(SKILLS_DST.rglob("*"), reverse=True):
            rel = path.relative_to(SKILLS_DST)
            if path.is_file() and rel not in sources:
                path.unlink()
                changed.append(str(Path(".claude/skills") / rel))
            elif path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    return changed


def main() -> int:
    """Refresh every mirror; return 1 if any was changed, else 0."""
    if not SOURCE.exists():
        raise FileNotFoundError(f"Skill source not found: {SOURCE}")
    changed = sync_docs() + mirror_skills()
    if changed:
        print(
            "Regenerated "
            + ", ".join(changed)
            + " from .agents/skills/. Stage them and commit again."
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
