"""Mirror the ``blond-dev`` skill into root CLAUDE.md and AGENTS.md.

The skill at ``.agents/skills/blond-dev/SKILL.md`` is the single source of
developer-onboarding text. This script copies its body (frontmatter stripped,
with a generated-file banner prepended) into ``CLAUDE.md`` and ``AGENTS.md`` at
the repo root, so interactive and CI/CD agents share the same context.

Run as a ``pre-commit`` hook: it only fires when the skill changes, and exits
non-zero if it had to rewrite either target so the new files get re-staged.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / ".agents" / "skills" / "blond-dev" / "SKILL.md"
TARGETS = (ROOT / "CLAUDE.md", ROOT / "AGENTS.md")

BANNER = (
    "<!--\n"
    "AUTO-GENERATED FILE - DO NOT EDIT.\n"
    "Source: .agents/skills/blond-dev/SKILL.md\n"
    "Regenerated by the `sync-agent-docs` pre-commit hook.\n"
    "Edit the skill, then commit; this file is rewritten automatically.\n"
    "-->\n\n"
)


def strip_frontmatter(text: str) -> str:
    """Return ``text`` without a leading YAML ``---`` frontmatter block."""
    if not text.startswith("---"):
        return text
    lines = text.splitlines(keepends=True)
    for index in range(1, len(lines)):
        if lines[index].rstrip("\n") == "---":
            return "".join(lines[index + 1 :]).lstrip("\n")
    return text


def render() -> str:
    """Build the generated document from the skill source."""
    body = strip_frontmatter(SOURCE.read_text(encoding="utf-8"))
    return BANNER + body


def main() -> int:
    """Rewrite stale targets; return 1 if any were changed, else 0."""
    if not SOURCE.exists():
        raise FileNotFoundError(f"Skill source not found: {SOURCE}")
    content = render()
    changed = []
    for target in TARGETS:
        old = target.read_text(encoding="utf-8") if target.exists() else None
        if old != content:
            target.write_text(content, encoding="utf-8", newline="\n")
            changed.append(target.name)
    if changed:
        print(
            "Regenerated "
            + ", ".join(changed)
            + " from .agents/skills/blond-dev/SKILL.md. "
            + "Stage them and commit again."
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
