# Copyright CERN. This software is distributed under the
# terms of the GNU General Public Licence version 3 (GPL Version 3),
# copied verbatim in the file LICENSE.txt.
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization or
# submit itself to any jurisdiction.
# Project website: http://blond.web.cern.ch/

"""
Wrap any xsuite element / line as a single black-box BLonD ring element.

The wrapper transports particles between BLonD's ``(dt, dE)`` and xsuite's
``(zeta, ptau)`` coordinates, runs the xsuite element's ``track``, and
tells the BLonD ring how long it is and how much reference time it
consumes — *nothing else*. It deliberately does not introspect what kind
of element it wraps. From BLonD's analytics' point of view (``phi_s``,
slip-factor averaging, voltage sums) the xsuite block is invisible.

This is the black-box treatment we want: xsuite owns its physics, BLonD
owns its loop, the wrapper is purely transport. If a user needs BLonD
to compute things that depend on the lattice (``phi_s``, eta_0
averaging), they add parallel BLonD elements with matching parameters
alongside the wrapper.
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING, Any

import numpy as np

from blond.core.beam.flags import BeamFlags
from blond.interfaces.xsuite.elements.helpers import (
    ReferenceFrame,
    dE_to_ptau,
    dt_to_zeta,
    ptau_to_dE,
    zeta_to_dt,
)
from blond.physics.cavities import RFStationBaseClass
from blond.physics.drifts import DriftBaseClass

if TYPE_CHECKING:  # pragma: no cover
    from xtrack import BeamElement, Line, Particles

    from blond.core.beam.base import BeamBaseClass
    from blond.core.reference_clock.reference_clock import ReferenceCoordinates
    from blond.core.simulation.simulation import Simulation

    # Any xsuite guest the wrapper accepts: a single beam element (Drift,
    # Cavity, Multipole, ReferenceEnergyIncrease, … — all subclass
    # ``BeamElement``) or a full ``Line``. Both expose ``track(particles)``.
    XsuiteTrackable = BeamElement | Line


def _to_numpy(array) -> np.ndarray:
    """
    Return a host numpy view of ``array``, copying off-GPU if needed.

    BLonD's ``beam.*.array_local`` storage is cupy when the backend is GPU;
    xsuite ``Particles`` in this wrapper are always numpy. ``.get()`` pulls a
    cupy array back to host; plain numpy / array-likes pass through
    ``np.asarray`` unchanged.

    Parameters
    ----------
    array
        A cupy array, numpy array or array-like.

    Returns
    -------
    numpy.ndarray
        A host numpy array.
    """
    if hasattr(array, "get"):
        return array.get()
    return np.asarray(array)


def _extract_length(element: XsuiteTrackable) -> float:
    r"""
    Return a finite drift length for an xsuite guest, or raise ``TypeError``.

    Works for single elements with ``.length`` (``xt.Drift``,
    ``xt.LineSegmentMap``, …) and for full ``xt.Line``\s via
    ``get_length()``. Raises for guests with no defined length (markers,
    apertures) — pass ``orbit_length=`` explicitly in that case.

    Parameters
    ----------
    element
        An xsuite element or line to measure.

    Returns
    -------
    float
        The orbit length [m].
    """
    length = getattr(element, "length", None)
    if length is not None:
        try:
            return float(length)
        except TypeError:
            return float(_to_numpy(length).item())
    if hasattr(element, "get_length"):
        return float(element.get_length())
    raise TypeError(
        f"Cannot determine an orbit length for xsuite guest "
        f"{type(element).__name__}; pass `orbit_length=` explicitly "
        f"(use 0.0 for markers / apertures with no spatial extent)."
    )


# TODO but later.
#  Have three distinct wrappers for
#  1. WrapXsuite4Blond(DriftBaseClass)
#  2. WrapXsuite4Blond(RFStationBaseClass)
#  3. WrapXsuite4Blond(RFStationBaseClass, DriftBaseClass)
#  1. and 2. should be autogenerated from the 3..
#  Then do 20260609.0 in ring.py
class WrapXsuite4Blond(RFStationBaseClass, DriftBaseClass):
    """
    Black-box wrapper of any xsuite element/line for use inside a BLonD ring.

    The wrapper subclasses both :class:`RFStationBaseClass` and
    :class:`DriftBaseClass`, so it is, by type, a first-class BLonD element
    that can stand in for an xsuite drift *or* cavity. For now only the
    transport path is mapped — ``_track`` (coordinate round-trip),
    ``track_reference`` (time advance + reference-energy probe) and
    ``orbit_length`` are real; everything else inherited from the two base
    classes (``eta_0``, ``get_main_harmonic*``,
    ``calc_main_harmonic_omega_rf_design``) raises
    :class:`NotImplementedError` until the richer cavity/optics features
    land.

    Because the wrapped element is opaque to BLonD's longitudinal analytics
    (``phi_s``, slip-factor averaging, voltage sums), the wrapper does not
    drive the reference energy and opts out of RF-station accounting via
    ``counts_as_rf_station = False`` — it must not inflate
    ``Ring.n_rf_stations``, which splits the magnetic-cycle energy increment
    per station. If you need ``phi_s`` or eta_0 averaging that includes the
    xsuite block, add parallel BLonD elements (a ``SingleHarmonicRFStation``,
    a ``DriftSimple``) carrying the matching parameters alongside it.

    Each call to ``_track``:

    1. Builds a :class:`ReferenceFrame` from ``beam.reference``.
    2. Pushes BLonD's current reference into the cached xsuite
       ``Particles`` so the guest sees a consistent ``(β₀, p0c, energy0)``.
    3. Propagates BLonD's LOST flag into xsuite's particle state via
       the ``particle_id`` mapping (xsuite reorders particles to keep
       active slots contiguous; the wrapper keeps BLonD slots stable).
    4. Converts ``(dt, dE)`` into ``(zeta, ptau)``.
    5. Calls ``self._xsuite_element.track(particles)``.
    6. If the guest moved ``particles.energy0`` (e.g. an
       ``xt.ReferenceEnergyIncrease`` element or a wrapped line with an
       ``EnergyProgram``), pushes the new total energy into
       ``beam.reference``.
    7. Writes active particles back into the beam; lost xsuite slots
       flag the matching BLonD slot ``LOST``.

    Parameters
    ----------
    xsuite_element
        Any xsuite object exposing ``track(particles)``. Drifts, RF
        cavities, transverse magnets, full lines — all work.
    orbit_length
        Override the guest's intrinsic length (or supply one for
        guests with no ``.length`` attribute). Defaults to
        ``_extract_length(xsuite_element)``.
    """

    skip_find_instances_attributes = ["_xsuite_element"]

    # The wrapper is an ``RFStationBaseClass`` by type so it can stand in for
    # an xsuite cavity, but it never drives BLonD's reference energy (its
    # ``track_reference`` only advances time + probes the guest). Opt out of
    # RF-station accounting so ``Ring.n_rf_stations`` — and thus the
    # ``MagneticCyclePerTurn`` energy split and the one-station-per-section
    # check — does not count it as an accelerating station.
    counts_as_rf_station = False  # FIXME 20260609.0

    def __init__(
        self,
        xsuite_element: XsuiteTrackable,
        orbit_length: float | None = None,
    ) -> None:
        self._xsuite_element = xsuite_element
        self._particles: Particles | None = None
        self._p0c_bufffer: np.ndarray | None = None

        # Refuse a wrapped ``xt.Line`` that carries its own ``EnergyProgram``:
        # BLonD owns the reference here and the wrapper's per-turn refresh
        # would overwrite the program's advance.
        if getattr(xsuite_element, "energy_program", None) is not None:
            raise ValueError(
                "WrapXsuite4Blond was given an xt.Line with an attached "
                "energy_program. BLonD owns the reference inside its Ring, "
                "and the wrapper's per-turn update_p0c would overwrite any "
                "program-driven advance. Either drive the ramp from BLonD's "
                "MagneticCycle (and remove the line's energy_program), or "
                "let xsuite own the loop and use WrapBlond4Xsuite instead."
            )

        resolved_length = (
            float(orbit_length)
            if orbit_length is not None
            else _extract_length(xsuite_element)
        )
        # Feed the cooperative RFStationBaseClass + DriftBaseClass __init__
        # chain. ``n_rf``/``section_index``/``local_wakefield`` satisfy the RF
        # base; ``orbit_length`` flows through to DriftBaseClass which stores
        # it. The RF parameters (voltage/harmonic/phi_rf) stay ``None`` — this
        # wrapper is a black box and never runs BLonD's RF physics.
        super().__init__(
            n_rf=1,
            section_index=0,
            local_wakefield=None,
            orbit_length=resolved_length,
        )

    # ------------------------------------------------------------------
    # Simulation lifecycle: bypass the RFStationBaseClass-specific hooks.
    #
    # RFStationBaseClass.on_init_simulation validates voltage/harmonic/
    # phi_rf_design (all intentionally ``None`` here), and its configure_run
    # computes the design omega via the stubbed RF methods. The wrapper is a
    # black box, so we skip straight to RFManipulationBaseClass's setup (which
    # binds ``_ring``/``_magnetic_cycle``/``_turn_counter``) and the plain
    # base configure_run.
    # ------------------------------------------------------------------

    def on_init_simulation(
        self, simulation: Simulation, **kwargs: Any
    ) -> None:
        """
        Run the base init-simulation hook, skipping RF-station setup.

        Parameters
        ----------
        simulation
            The simulation being initialised.
        **kwargs
            Forwarded to the base hook.
        """
        super(RFStationBaseClass, self).on_init_simulation( # FIXME not only RFStationBaseClass
            simulation=simulation, **kwargs
        )

    def configure_run(
        self, beam: BeamBaseClass, n_turns: int, **kwargs: Any
    ) -> None:
        """
        Run the base configure-run hook, skipping RF-station setup.

        Parameters
        ----------
        beam
            The beam to be tracked.
        n_turns
            Number of turns to be tracked.
        **kwargs
            Forwarded to the base hook.
        """
        super(RFStationBaseClass, self).configure_run(  # FIXME not only RFStationBaseClass
            beam=beam, n_turns=n_turns, **kwargs
        )

    # ------------------------------------------------------------------
    # Abstract members of the two base classes that this black-box wrapper
    # does not (yet) map. The wrapped xsuite element owns this physics; if a
    # user needs BLonD-side phi_s / eta_0 analytics they add parallel BLonD
    # elements. These are wired up only when the richer features land.
    # ------------------------------------------------------------------

    _NOT_MAPPED = (
        "`WrapXsuite4Blond` is a black-box transport wrapper; `{name}` is not "
        "mapped. The wrapped xsuite element owns its RF/optics physics. Add a "
        "parallel BLonD element (SingleHarmonicRFStation / DriftSimple) with "
        "matching parameters if you need BLonD-side analytics."
    )

    def eta_0(self, gamma: float) -> float:
        """
        Not mapped by this black-box wrapper (raises).

        Parameters
        ----------
        gamma
            Reference relativistic gamma [1].
        """
        raise NotImplementedError(self._NOT_MAPPED.format(name="eta_0"))

    def get_main_harmonic(self) -> float:
        """Not mapped by this black-box wrapper (raises)."""
        raise NotImplementedError(
            self._NOT_MAPPED.format(name="get_main_harmonic")
        )

    def get_main_harmonic_voltage(self) -> float:
        """Not mapped by this black-box wrapper (raises)."""
        raise NotImplementedError(
            self._NOT_MAPPED.format(name="get_main_harmonic_voltage")
        )

    def get_main_harmonic_phi_rf(self) -> float:
        """Not mapped by this black-box wrapper (raises)."""
        raise NotImplementedError(
            self._NOT_MAPPED.format(name="get_main_harmonic_phi_rf")
        )

    def calc_main_harmonic_omega_rf_design(
        self, beam_beta: float, ring_circumference: float
    ) -> float:
        """
        Not mapped by this black-box wrapper (raises).

        Parameters
        ----------
        beam_beta
            Reference relativistic beta [1].
        ring_circumference
            Ring circumference [m].
        """
        raise NotImplementedError(
            self._NOT_MAPPED.format(name="calc_main_harmonic_omega_rf_design")
        )

    def get_main_harmonic_omega_rf(self) -> float:
        """Not mapped by this black-box wrapper (raises)."""
        raise NotImplementedError(
            self._NOT_MAPPED.format(name="get_main_harmonic_omega_rf")
        )

    def track_reference(
        self,
        reference: ReferenceCoordinates,
        is_counter_rotating: bool = False,
        **kwargs,
    ) -> float:
        """
        Advance the reference clock — both time and (probed) total energy.

        Time advance is ``orbit_length / β c`` (time-of-flight at the
        current reference velocity, geometric definition).

        Total-energy advance is *observed*, not assumed: we send a fresh
        single synchronous probe particle (``zeta = 0``, ``ptau = 0``)
        through the guest's ``track`` and read what changed on the
        probe's ``energy0``. This catches reference-advancing guests
        (``xt.ReferenceEnergyIncrease``, an ``xt.Line`` containing one,
        a Line with internal ``EnergyProgram``) without us having to
        know which they are. Returns the energy delta (the time delta
        is already written into ``reference.time``).

        The probe is a fresh ``Particles`` object every call so the
        guest doesn't see any carry-over state. If the guest kills the
        synchronous probe (aperture / loss element at zeta=0) we treat
        the energy delta as zero and don't raise — that's an unusual
        configuration but not our problem to police.

        Counter-rotating beams are not supported: the wrapper tracks the
        guest in a single orbit direction only, so it raises
        :class:`NotImplementedError` rather than silently returning a
        wrong reference advance.

        Parameters
        ----------
        reference
            Reference coordinates whose ``time`` and ``total_energy`` are
            advanced in place.
        is_counter_rotating
            Must be ``False``; counter-rotating beams are not supported.
        **kwargs
            Ignored; accepted for interface compatibility.

        Returns
        -------
        float
            The reference total-energy delta [eV] applied this call.
        """
        if is_counter_rotating:
            raise NotImplementedError(
                "WrapXsuite4Blond does not support counter-rotating beams; "
                "the wrapped xsuite element is tracked in a single orbit "
                "direction only."
            )
        # fixme why twice? xsuite and local calculations
        reference_time_change = self.orbit_length / reference.velocity
        reference.time += reference_time_change

        from xtrack import Particles

        mass = float(reference.particle_type.mass)
        p0c_now = math.sqrt(reference.total_energy**2 - mass**2)
        probe = Particles(
            p0c=p0c_now,
            mass0=mass,
            q0=float(reference.particle_type.charge),
            zeta=np.zeros(1),
            ptau=np.zeros(1),
        )
        self._xsuite_element.track(probe)

        if int(np.asarray(probe.state)[0]) <= 0:
            # Aperture / loss element killed the synchronous probe —
            # can't infer a reference advance, leave total_energy alone.
            return 0.0

        new_e0 = float(np.asarray(probe.energy0)[0])
        delta_e = new_e0 - reference.total_energy
        reference.total_energy = new_e0
        return delta_e

    def _build_particles(
        self, beam: BeamBaseClass, energy0: float, n: int
    ) -> None:
        from xtrack import Particles

        mass = float(beam.particle_type.mass)
        p0c = float(math.sqrt(energy0**2 - mass**2))
        self._particles = Particles(
            p0c=p0c,
            mass0=mass,
            q0=float(beam.particle_type.charge),
            zeta=np.zeros(n),
            ptau=np.zeros(n),
        )
        self._p0c_bufffer = np.full(n, p0c)

    def _track(self, beam: BeamBaseClass) -> None:
        beta0 = float(beam.reference.beta)
        energy0 = float(beam.reference.total_energy)
        frame = ReferenceFrame(beta0=beta0, energy0=energy0)

        n = len(beam.dt.array_local)

        if self._particles is None or self._particles.zeta.shape[0] != n:
            self._build_particles(beam, energy0, n)
        else:
            mass = float(beam.particle_type.mass)
            new_p0c = float(math.sqrt(energy0**2 - mass**2))
            self._p0c_bufffer.fill(new_p0c)
            self._particles.update_p0c(self._p0c_bufffer)

        # xsuite Particles are numpy in our wrapper (we build them with
        # ``np.zeros``), so ``particles.*`` reads are plain numpy.
        # BLonD-side ``beam.*.array_local`` may be cupy if BLonD's backend
        # is GPU — ``_to_numpy`` handles that via ``.get()``.
        # FIXME we want xsuite backend gpu when blond backend is gpu,
        #  then this shouldn't be necessary..
        pid_in = np.asarray(self._particles.particle_id)
        blond_flags = _to_numpy(beam.flags.array_local)
        blond_dt = _to_numpy(beam.dt.array_local)
        blond_dE = _to_numpy(beam.dE.array_local)
        blond_active = blond_flags == BeamFlags.ACTIVE.value

        # Mark xsuite slots as lost when their mapped BLonD slot is lost.
        self._particles.state[~blond_active[pid_in]] = -1

        self._particles.zeta[:] = dt_to_zeta(blond_dt[pid_in], frame)
        self._particles.ptau[:] = dE_to_ptau(blond_dE[pid_in], frame)

        self._xsuite_element.track(self._particles)

        pid_out = np.asarray(self._particles.particle_id)
        active_xs = np.asarray(self._particles.state) > 0

        # Pick up any reference advance the guest performed.
        if active_xs.any():
            i = int(np.argmax(active_xs))
            new_energy0 = float(np.asarray(self._particles.energy0)[i])
            if new_energy0 != energy0:
                beam.reference.total_energy = new_energy0
                frame = ReferenceFrame(
                    beta0=float(np.asarray(self._particles.beta0)[i]),
                    energy0=new_energy0,
                )

        active_slots = pid_out[active_xs]
        new_dt = zeta_to_dt(np.asarray(self._particles.zeta)[active_xs], frame)
        new_dE = ptau_to_dE(np.asarray(self._particles.ptau)[active_xs], frame)
        # Direct assignment into BLonD storage handles the numpy → backend
        # promotion (cupy's ``__setitem__`` accepts numpy on the rhs).
        beam.dt.array_local[active_slots] = new_dt
        beam.dE.array_local[active_slots] = new_dE
        if not active_xs.all():
            beam.flags.array_local[pid_out[~active_xs]] = BeamFlags.LOST.value
