"""BLonD documentation build configuration file.

BLonD documentation build configuration file, created by
sphinx-quickstart on Fri Mar 10 19:37:27 2017.

This file is execfile() with the current directory set to its
containing dir.

Note that not all possible configuration values are present in this
autogenerated file.

All configuration values have a default; values that are commented out
serve to show the default.

If extensions (or modules to document with autodoc) are in another directory,
add these directories to sys.path here. If the directory is relative to the
documentation root, use os.path.abspath to make it absolute, like shown here.
"""

import datetime
import os
import sys
from importlib.metadata import version as get_version

from intersphinx_registry import get_intersphinx_mapping

print(">>> Sphinx loaded THIS conf.py:", __file__)

sys.path.insert(0, os.path.abspath(".."))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = "1.0"


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom
# ones.

os.environ["SPHINX_SHOW_WARNING_TYPES"] = "1"  # force categories in output

folder = os.path.abspath("modules")
sys.path.insert(0, folder)
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "numpydoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "sphinx.ext.inheritance_diagram",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
    "nbsphinx",
]
# From https://nbsphinx.readthedocs.io/en/0.8.9/custom-css.html#For-a-Single-Notebook
# Hide the [1], [2], etc. displays at
# the left side of the Jupyter-Notebook cells.
nbsphinx_prolog = """
.. raw:: html

    <style>
        .nbinput .prompt,
        .nboutput .prompt {
            display: none;
        }
    </style>
"""

autosummary_generate = True
autosummary_imported_members = True
napoleon_use_param = True

inheritance_graph_attrs = {
    "rankdir": "TB",  # "TB" = Top → Bottom (vertical)
    "size": '"12.0, 10.0"',  # adjust as needed (width,height in inches)
    "fontsize": 14,
    "ranksep": "0.4",
    "nodesep": "0.2",
    "layout": "dot",
}

numpydoc_show_class_members = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = [".rst", ".md"]
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.

project = "BLonD"
copyright = "2014 - " + str(datetime.datetime.now().year)
author = "BLonD-admin"

autodoc_mock_imports = ["mpi4py"]

# The version info for the project you"re documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#


# The short X.Y version.
version = ".".join(get_version("blond").split(".")[:3])
# The full version, including alpha/beta/rc tags.
release = get_version("blond")

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
# exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "_themes"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "*/blond.core.backends.cpp.compiled.*",
    "*/blond.core.backends.cuda.compiled.*",
    "*/blond.legacy.*",
    "*/blond.performance_blond3.*",
    "*/blond.experimental.*",
    "*/blond.examples.*",
    "*/blond._versio*",
    "*/blond.core.backends.cuda.call*",
    "*/blond.core.backends.cpp.call*",
    "*/blond.core.backends.cpp.lib*",
    "*/blond.generals._files*",
    "*/blond.generals._hashing*",
    "*vari_noise*",
    "*/blond.testing.*",
    "*/blond.interfaces.xsuite.*",
    "*/blond.specifics.cern.*",  # empty at the moment
]
# callables are only importable with cupy compiled

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
# todo_include_todos = True

setuptools_scm_git_archive = False

autodoc_member_order = "bysource"
autodoc_preserve_defaults = True  # optional
# autodoc_inherit_docstrings = False
autodoc_typehints = "signature"  # or 'description'

autodoc_search_path = [os.path.abspath("../")]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "show_prev_next": False,
    "navbar_end": ["theme-switcher", "navbar-icon-links.html"],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/numpy/numpydoc",
            "icon": "fab fa-github-square",
            "type": "fontawesome",
        },
    ],
}

html_sidebars = {
    "**": [],
}
html_context = {
    "default_mode": "light",
}

html_title = f"{project} v{version} Manual"
html_last_updated_fmt = "%b %d, %Y"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []  # ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = "BLonD Documentation"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ("letterpaper" or "a4paper").
    #
    # "papersize": "letterpaper",
    # The font size ("10pt", "11pt" or "12pt").
    #
    # "pointsize": "10pt",
    # Additional stuff for the LaTeX preamble.
    #
    # "preamble": "",
    # Latex figure (float) alignment
    #
    # "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "BLonD.tex", "BLonD Documentation", "Test", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "blond", "BLonD Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "BLonD",
        "BLonD Documentation",
        author,
        "BLonD",
        "One line description of project.",
        "Miscellaneous",
    ),
]

rst_prolog = """
.. role:: center
   :class: center
"""  # allow for :center:

suppress_warnings = [
    "autodoc.duplicate_object",
    "toc.excluded",
    "ref.python",
    "docutils",
    "python.duplicate_object",
    "py.duplicate_object",  # Sphinx 6+: inherited members re-documented under child class
]  # remove warning for multiple mentions of the same item
html_static_path = ["_static"]
html_css_files = ["css/wide.css"]

autodoc_default_options = {
    # Avoid pulling in names that are only imported into __init__.py
    # "imported-members": False,  # breaks import location
    "show-inheritance": True,
    "no-imported-members": True,
    "inherited-members": True,
}

show_warning_types = True


# Required to skip instances of _abc_impl, which are present in
# all classes inheriting from ABC (which is almost all our classes)
def skip_specific_functions(app, what, name, obj, skip, options):
    """
    Determine whether Sphinx should skip documenting a specific member.

    This function is used as a callback for the
    ``autodoc-skip-member`` event in Sphinx. It allows selectively
    skipping members during the autodoc process. In this case, the
    function skips the internal member ``_abc_impl`` while deferring
    to Sphinx’s default behavior for all other members.

    Parameters
    ----------
    app : sphinx.application.Sphinx
        The Sphinx application object.
    what : str
        The type of the object being documented (e.g., ``"module"``,
        ``"class"``, ``"method"``, etc.).
    name : str
        The fully qualified name of the member.
    obj : object
        The member object itself.
    skip : bool
        The current skip decision made by Sphinx. If ``True``, Sphinx
        already intends to skip this member.
    options : sphinx.ext.autodoc.Options
        Additional options passed to autodoc about the member.

    Returns
    -------
    bool
        ``True`` if the member should be skipped,
        ``False`` otherwise. Members named ``"_abc_impl"`` are always
        skipped.
    """
    if name == "_abc_impl":
        return True
    return skip


def setup(app):
    """
    Register Sphinx event handlers for this extension.

    Parameters
    ----------
    app : sphinx.application.Sphinx
        The Sphinx application object.

    Returns
    -------
    None
    """
    app.connect("autodoc-skip-member", skip_specific_functions)


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = get_intersphinx_mapping(
    packages=["python", "numpy", "scipy", "sklearn"]
)
