# coding: utf-8
# Copyright 2016 CERN. This software is distributed under the
# terms of the GNU General Public Licence version 3 (GPL Version 3),
# copied verbatim in the file LICENCE.md.
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization or
# submit itself to any jurisdiction.
# Project website: http://blond.web.cern.ch/

'''
**Module to compute beam slicing for a sparse beam**
**Only valid for cases with constant revolution and RF frequencies**

:Authors: **Juan F. Esteban Mueller**
'''

from __future__ import division, print_function

import copy
from builtins import range

import numpy as np
from .beam import Beam
from ..beam.profile import CutOptions, Profile
from ..utils import bmath as bm

class _SparseBaseClass:
    "Base class for sparse profiles"

    def __init__(self, RFStation, Beam,
                 number_of_slices_per_profile,
                 tracker='C',
                 direct_slicing=False):
        """

        :param RFStation:
        :param Beam:
        :param number_of_slices_per_profile:
        :param tracker:
        :param direct_slicing:
        """


        self.Beam = Beam
        self.energy = Beam.energy
        self.RFParams = RFStation

        #: *Number of slices per bucket*
        self.number_of_slices_per_profile = number_of_slices_per_profile
        self.n_slices = None
        self.profiles_list = None
        # Group n_macroparticles from all objects in a single array
        # (for C++ track).
        self.n_macroparticles_array = None
        self.bin_centers_array =None
        self.edges_array =None
        self.n_macroparticles = None
        self.bin_centers = None
        self.bin_size = None

        self.cut_left_array = None
        self.cut_right_array  = None
        self.bunch_indexes = None

        self.tracker = tracker
        self.direct_slicing = direct_slicing
        self.track = None


    def generate_profile_list(self):
        pass

    def set_cuts(self):
        pass

    def _init_general_arrays(self):
        """
        Method to update the general arrays after a profile update.
        """
        self.n_macroparticles = np.concatenate(self.n_macroparticles_array,
                                               axis=0)
        self.bin_centers = np.concatenate(self.bin_centers_array, axis=0)
        self.bin_size = self.profiles_list[0].bin_size
        self.n_slices = self.number_of_slices_per_profile * len(self.profiles_list)

    def set_tracker(self):
        if self.tracker == 'C':
            self.track = self._histogram_c
        elif self.tracker == 'onebyone':
            self.track = self._histogram_one_by_one
        else:
            # WrongCalcError
            raise RuntimeError(
                'Tracking method not recognized!')

        # Track at initialisation
        if self.direct_slicing:
            self.track()

    def _histogram_c(self):
        '''
        *Histogram generated by calling an optimized C++ function that
        calculates all the profile at once.*
        '''
        bm.sparse_histogram(self.Beam.dt, self.n_macroparticles_array,
                            self.cut_left_array, self.cut_right_array,
                            self.bunch_indexes, self.number_of_slices_per_profile)

    def _histogram_one_by_one(self):
        '''
        *Histogram generated by calling the tack() method of each Profile
        object*
        '''

        for i in range(len(self.profiles_list)):
            self.profiles_list[i].track()
            self.bin_centers_array[i, :] = self.profiles_list[i].bin_centers
            self.n_macroparticles_array[i, :] = self.profiles_list[
                i].n_macroparticles
        self.bin_centers = np.concatenate(self.bin_centers_array, axis = 0)
        self.n_macroparticles = np.concatenate(self.n_macroparticles_array,
                                               axis=0)

class SparseBucket(_SparseBaseClass):
    '''
    *This class instantiates a Profile object for each filled bucket according
    to the provided filling pattern/bunch list. Each Profile object will be of
    the size of
    an RF bucket and will have the same number of slices.*
    '''

    def __init__(self, RFStation, Beam,
                 number_of_slices_per_profile,
                 bunch_list, tracker='C',
                 direct_slicing=False):
        #: *Filling pattern as a boolean array where True (1) means filled
        # bucket*
        super().__init__(RFStation, Beam, number_of_slices_per_profile, tracker,
                         direct_slicing)

        self.bunch_list = bunch_list
        self.bunch_indexes = np.cumsum(bunch_list) * bunch_list - 1
        self.n_filled_buckets = int(np.sum(bunch_list))

        # Pre-processing the slicing edges
        self.set_cuts()
        self.generate_profile_list()
        self.set_tracker()

    def generate_profile_list(self):
        self.profiles_list = []
        self.n_macroparticles_array = np.zeros((self.n_filled_buckets,
                                                self.number_of_slices_per_profile))
        self.bin_centers_array = np.zeros(
            (self.n_filled_buckets, self.number_of_slices_per_profile))
        self.edges_array = np.zeros(
            (self.n_filled_buckets, self.number_of_slices_per_profile + 1))

        for i in range(self.n_filled_buckets):
            # Only valid for cut_edges='edges'

            self.profiles_list.append(
                Profile(self.Beam, CutOptions(cut_left=self.cut_left_array[i],
                                              cut_right=self.cut_right_array[
                                                  i],
                                              n_slices=self.number_of_slices_per_profile)))
            self.n_macroparticles_array[i, :] = self.profiles_list[
                i].n_macroparticles
            self.bin_centers_array[i, :] = self.profiles_list[i].bin_centers
            self.edges_array[i, :] = self.profiles_list[i].edges
        self._init_general_arrays()

    def set_cuts(self):
        '''
        *Method to set the self.cut_left_array and self.cut_right_array
        properties, with the limits being an RF period.
        This is done as a pre-processing.*

        Parameters
        ----------
        bucket_margin
            Extend the scope of the Profile objects to the neighbouring buckets.
        '''
        # RF period
        t_rf = self.RFParams.t_rf[0, self.RFParams.counter[0]]

        self.cut_left_array = np.zeros(self.n_filled_buckets)
        self.cut_right_array = np.zeros(self.n_filled_buckets)
        for i in range(self.n_filled_buckets):
            bucket_index = np.where(self.bunch_list)[0][i]
            self.cut_left_array[i] = bucket_index * t_rf
            self.cut_right_array[i] = (bucket_index + 1 ) * t_rf

    def _set_additional_cuts(self,
                            updated_bunch_list,
                            ):
        '''
        *Method to update set the self.cut_left_array and
        self.cut_right_array
        properties with additional filled buckets.*
        '''
        # RF period
        t_rf = self.RFParams.t_rf[0, self.RFParams.counter[0]]
        current_bunch_list = self.bunch_list

        filled_bunches_current = np.where(current_bunch_list)[0]
        filled_bunches_new = np.where(updated_bunch_list)[0]
        additional_filled_buckets = len(filled_bunches_new) - len(filled_bunches_current)

        mask_additional_bunch = copy.deepcopy(current_bunch_list)
        for i in filled_bunches_new:
            if current_bunch_list[i] == 0:
                mask_additional_bunch[i] = 1
            else:
                mask_additional_bunch[i] = 0
        #fixme: injected bunch might be between already considered bunches
        updated_cut_left = np.zeros(additional_filled_buckets)
        updated_cut_right = np.zeros(additional_filled_buckets)
        for i in range(additional_filled_buckets):
            bucket_index = np.where(mask_additional_bunch)[0][i]
            updated_cut_left[i] = bucket_index * t_rf
            updated_cut_right[i] = (bucket_index + 1) * t_rf
        self.cut_left_array = np.append(self.cut_left_array, updated_cut_left)
        self.cut_right_array = np.append(self.cut_right_array,
                                        updated_cut_right)
        self.bunch_list = updated_bunch_list
        return additional_filled_buckets

    def _update_profile_lists(self,
                            additional_filled_buckets: int,
                            ):
        '''
        *Method to update create individual profiles for the injected
        bunches*
        '''
        # Initialize individual slicing objects
        profiles_list_additional = []
        if (len(self.cut_right_array) != self.n_filled_buckets +
                additional_filled_buckets) or (len(self.cut_left_array) !=
                                               self.n_filled_buckets +
                additional_filled_buckets):
            raise ValueError('Cut arrays have not been updated.')
        if (len(np.where(self.bunch_list)[0]) != self.n_filled_buckets +
                additional_filled_buckets):
            raise ValueError('Filling pattern has not been updated.')

        for i in range(additional_filled_buckets):
            # Only valid for cut_edges='edges'
            profiles_list_additional.append(
                Profile(self.Beam, CutOptions(cut_left=self.cut_left_array[
                    self.n_filled_buckets + i],
                                         cut_right=self.cut_right_array[self.n_filled_buckets + i],
                                         n_slices=self.number_of_slices_per_profile)))
            self.n_macroparticles_array = np.insert(
                arr=self.n_macroparticles_array,
                obj = len(self.n_macroparticles_array),
                values = profiles_list_additional[i].n_macroparticles,
                axis=0,
            )
            self.bin_centers_array = np.insert(
                arr=self.bin_centers_array,
                obj = len(self.bin_centers_array),
                values = profiles_list_additional[i].bin_centers,
                axis=0,
            )
            self.edges_array = np.insert(
                arr=self.edges_array,
                obj = len(self.edges_array),
                values = profiles_list_additional[i].edges,
                axis=0,
            )
        self.profiles_list = np.append(self.profiles_list, profiles_list_additional)
        self.n_filled_buckets += additional_filled_buckets
        self._update_general_arrays()


    def _update_general_arrays(self):
        """
        Method to update the general arrays after a profile update.
        """
        # Total parameters
        if len(np.where(self.bunch_list)[0]) != self.n_filled_buckets:
            raise ValueError(f'Filling pattern has length '
                             f'{len(np.where(self.bunch_list)[0])}, number of '
                             f'declared filled buckets '
                             f'{self.n_filled_buckets}.')
        self.bunch_indexes = np.cumsum(
            self.bunch_list) * self.bunch_list - 1
        self._init_general_arrays()

    def update_bunch_list(self, beam: Beam,
                              updated_bunch_list: list[int],
                              ):
        additional_filled_buckets = self._set_additional_cuts(
            updated_bunch_list = updated_bunch_list)
        self._update_profile_lists(additional_filled_buckets = additional_filled_buckets)

class SparseBatch(_SparseBaseClass):
    '''
    *This class instantiates a Profile object for each batch according
    to the provided batch list.
    Each Profile object will be of the size of
    a batch and will have the same number of slices.*
    '''

    def __init__(self, RFStation, Beam,
                 number_of_slices_per_profile,
                 batch_list, tracker='C',
                 batch_length :int = 0,
                 direct_slicing=False):

        #: *Filling pattern as a boolean array where True (1) means filled
        # bucket*
        super().__init__(RFStation, Beam, number_of_slices_per_profile,
                         tracker,
                         direct_slicing)
        #: *Filling pattern as a boolean array where True (1) means filled
        # bucket*
        self.batch_list = batch_list
        self.batch_length = batch_length

        # Index of each batch (-1 if empty). Only for C++ track
        self.batch_indexes = np.cumsum(batch_list) * batch_list - 1

        #: *Number of buckets to be sliced*
        self.number_of_batches = int(np.sum(batch_list))

        # Pre-processing the slicing edges
        self.set_cuts()
        self.generate_profile_list()
        self.set_tracker()

    def generate_profile_list(self):
        self.profiles_list = []
        self.n_macroparticles_array = np.zeros((self.number_of_batches,
                                                self.number_of_slices_per_profile))
        self.bin_centers_array = np.zeros(
            (self.number_of_batches, self.number_of_slices_per_profile))
        self.edges_array = np.zeros(
            (self.number_of_batches, self.number_of_slices_per_profile + 1))

        for i in range(self.number_of_batches):
            # Only valid for cut_edges='edges'

            self.profiles_list.append(
                Profile(self.Beam, CutOptions(cut_left=self.cut_left_array[i],
                                              cut_right=self.cut_right_array[
                                                  i],
                                              n_slices=self.number_of_slices_per_profile)))
            self.n_macroparticles_array[i, :] = self.profiles_list[
                i].n_macroparticles
            self.bin_centers_array[i, :] = self.profiles_list[i].bin_centers
            self.edges_array[i, :] = self.profiles_list[i].edges
        self._init_general_arrays()

    def set_cuts(self):
        '''
        *Method to set the self.cut_left_array and self.cut_right_array
        properties, with the limits being an RF period.
        This is done as a pre-processing.*

        Parameters
        ----------
        bucket_margin
            Extend the scope of the Profile objects to the neighbouring buckets.
        '''
        # RF period
        t_rf = self.RFParams.t_rf[0, self.RFParams.counter[0]]

        self.cut_left_array = np.zeros(self.number_of_batches)
        self.cut_right_array = np.zeros(self.number_of_batches)
        for i in range(self.number_of_batches):
            batch_index = np.where(self.batch_list)[0][i]
            self.cut_left_array[i] = batch_index * t_rf
            self.cut_right_array[i] = ((batch_index + self.batch_length) *
                                       t_rf)

    def _set_additional_cuts(self,
                            updated_batch_list,
                            ):
        '''
        *Method to update set the self.cut_left_array and
        self.cut_right_array
        properties with additional filled buckets.*
        '''
        # RF period
        t_rf = self.RFParams.t_rf[0, self.RFParams.counter[0]]
        current_batch_list = self.batch_list

        filled_batches_current = np.where(current_batch_list)[0]
        filled_batches_new = np.where(updated_batch_list)[0]
        additional_batches = len(filled_batches_new) - len(filled_batches_current)

        mask_additional_bunch = copy.deepcopy(current_batch_list)
        for i in filled_batches_new:
            if current_batch_list[i] == 0:
                mask_additional_bunch[i] = 1
            else:
                mask_additional_bunch[i] = 0
        #fixme: injected bunch might be between already considered bunches
        updated_cut_left = np.zeros(additional_batches)
        updated_cut_right = np.zeros(additional_batches)
        for i in range(additional_batches):
            batch_index = np.where(mask_additional_bunch)[0][i]
            updated_cut_left[i] = batch_index * t_rf
            updated_cut_right[i] = (batch_index + self.batch_length) * t_rf
        self.cut_left_array = np.append(self.cut_left_array, updated_cut_left)
        self.cut_right_array = np.append(self.cut_right_array,
                                        updated_cut_right)
        self.batch_list = updated_batch_list
        return additional_batches

    def _update_profile_lists(self,
                            additional_batches: int,
                            ):
        '''
        *Method to update create individual profiles for the injected
        bunches*
        '''
        # Initialize individual slicing objects
        profiles_list_additional = []
        if (len(self.cut_right_array) != self.number_of_batches +
                additional_batches) or (len(self.cut_left_array) !=
                                               self.number_of_batches +
                additional_batches):
            raise ValueError('Cut arrays have not been updated.')
        if (len(np.where(self.batch_list)[0]) != self.number_of_batches +
                additional_batches):
            raise ValueError('Filling pattern has not been updated.')

        for i in range(additional_batches):
            # Only valid for cut_edges='edges'
            # Only valid for cut_edges='edges'
            profiles_list_additional.append(
                Profile(self.Beam, CutOptions(cut_left=self.cut_left_array[
                    self.number_of_batches + i],
                                         cut_right=self.cut_right_array[self.number_of_batches + i],
                                         n_slices=self.number_of_slices_per_profile)))
            self.n_macroparticles_array = np.insert(
                arr=self.n_macroparticles_array,
                obj = len(self.n_macroparticles_array),
                values = profiles_list_additional[i].n_macroparticles,
                axis=0,
            )
            self.bin_centers_array = np.insert(
                arr=self.bin_centers_array,
                obj = len(self.bin_centers_array),
                values = profiles_list_additional[i].bin_centers,
                axis=0,
            )
            self.edges_array = np.insert(
                arr=self.edges_array,
                obj = len(self.edges_array),
                values = profiles_list_additional[i].edges,
                axis=0,
            )
        self.profiles_list = np.append(self.profiles_list, profiles_list_additional)
        self.number_of_batches += additional_batches
        self._update_general_arrays()


    def _update_general_arrays(self):
        """
        Method to update the general arrays after a profile update.
        """
        # Total parameters
        if len(np.where(self.batch_list)[0]) != self.number_of_batches:
            raise ValueError(f'Filling pattern has length '
                             f'{len(np.where(self.batch_list)[0])}, number of '
                             f'declared filled buckets '
                             f'{self.number_of_batches}.')
        self.n_macroparticles = np.concatenate(self.n_macroparticles_array,
                                               axis=0)
        self.n_slices = int(self.number_of_slices_per_profile * self.batch_list.sum())
        self.bunch_indexes = np.cumsum(
            self.batch_list) * self.batch_list - 1
        self.bin_centers = np.concatenate(self.bin_centers_array, axis=0)
        self.bin_size = self.profiles_list[0].bin_size

    def update_batch_list(self,
                              updated_batch_list: list[int],
                              ):
        additional_batches = self._set_additional_cuts(
            updated_batch_list = updated_batch_list)
        self._update_profile_lists(additional_batches =
                                   additional_batches)
